### ISSUE TITLE
400 The SSL certificate error

### ISSUE THREAD

**Issue by KrasilnikovKB** [orangedata-official/PHP-OrangeData-official#16]
Из имеющегося набора ключей/сертификатов:
```
1234567890.crt
1234567890.key
1234567890.pfx
cacert.pem
client_ca.crt
rsa_2048_private_key.pem
rsa_2048_private_key.xml
rsa_2048_public_key.xml
```
какой из них какой переменной присваивать?

```
     * @param string $sign_pkey - Path to signing private key or his PEM body
     * @param string $client_key - Path to client private key
     * @param string $client_cert - Path to Client 2SSL Certificate
     * @param string $ca_cert - Path to CA Certificate
```

опробовал уже всяко-всяко, но всегда получаю ошибку
**400 The SSL certificate error**

**Comment by Grigoriy-Kucenko** [comment]
Ghbdtn

> Из имеющегося набора ключей/сертификатов:
> 
> ```
> 1234567890.crt
> 1234567890.key
> 1234567890.pfx
> cacert.pem
> client_ca.crt
> rsa_2048_private_key.pem
> rsa_2048_private_key.xml
> rsa_2048_public_key.xml
> ```
> 
> какой из них какой переменной присваивать?
> 
> ```
>      * @param string $sign_pkey - Path to signing private key or his PEM body
>      * @param string $client_key - Path to client private key
>      * @param string $client_cert - Path to Client 2SSL Certificate
>      * @param string $ca_cert - Path to CA Certificate
> ```
> 
> опробовал уже всяко-всяко, но всегда получаю ошибку
> **400 The SSL certificate error**

Приветствую!

Как решил проблему?

**Comment by KrasilnikovKB** [comment]
я это как написал - так и забыл.

единственное - у меня конфиг для каждой кассы хранится в БД вот в таком виде (может чем то поможет) :

![image](https://user-images.githubusercontent.com/16627494/127840169-15a78f7a-634e-4ef3-942b-ad8bdee73071.png)

**Comment by Grigoriy-Kucenko** [comment]
Спасибо! Разобрался.

Правильно расставил сертификаты, скачал свежий ключ, указал правильный url для интерфейса...

В общем сделал всё аккуратно и заработало.
