### ISSUE TITLE
Ставка ндс 20% и 20/120 

### ISSUE THREAD

**Issue by Kabudasay** [orangedata-official/PHP-OrangeData-official#18]
*      1 – ставка НДС 18%
     *      2 – ставка НДС 10%
     *      3 – ставка НДС расч. 18/118
     *      4 – ставка НДС расч. 10/110
     *      5 – ставка НДС 0%
     *      6 – НДС не облагается

**Comment by silent105** [comment]
Спасибо за замечание.
Будет исправлено в версии 3.0.0
