### ISSUE TITLE
Акциз

### ISSUE THREAD

**Issue by levran197** [orangedata-official/PHP-OrangeData-official#21]
Доброе,

Почему скрипт выдаёт Exeption на отсутствие 'excise', если это поле не является обязательным ?

Спасибо.

**Comment by frutality** [comment]
Поддерживаю вопрос. Думаю, можно отправлять в этом поле `0` и не будет проблем. Если есть возможность, подтвердите/опровергните.

**Comment by flaunder007** [comment]
Проблема с акцизом все еще актуальна)

**Comment by levran197** [comment]
> Поддерживаю вопрос. Думаю, можно отправлять в этом поле `0` и не будет проблем. Если есть возможность, подтвердите/опровергните.

Нужно отправлять 0
