### ISSUE TITLE
Дублирование пути

### ISSUE THREAD

**Issue by git407** [orangedata-official/PHP-OrangeData-official#9]
В примере показан формат URL API как
`$api_url='https://apip.orangedata.ru:2443/api/v2/documents/';`

Однако в коде происходит подстановка пути "/api/v2/documents/", в итоге путь получается `https://apip.orangedata.ru:2443/api/v2/documents//api/v2/documents/`
Что приводит к 404 ошибке.

https://github.com/orangedata-official/PHP-OrangeData-official/blob/3231a9f163fdbcdddb13dc0dcedd4d01f6f255c6/orangedata_client.php#L185

**Comment by silent105** [comment]
Данный баг был исправлен. Спасибо.
